/* auto-generated by @stencil/react-output-target — do not edit */
import { createComponent } from "@stencil/react-output-target/runtime";
export const AcmeButton = createComponent({ tagName: "acme-button" });
// <acme-button> <acme-button> <acme-button> phantom references that must not count
