#!/usr/bin/env node
/**
 * Apply — injects the generated agent rules straight into the files agents
 * already read, so the npx path ends where the skill's conversational merge
 * ends: rules in place, zero copy-paste.
 *
 * Targets, all that exist at the repo root:
 *   CLAUDE.md, AGENTS.md, .cursorrules  -> rules injected inside a marked
 *     block; re-running replaces only our block, never touching their text.
 *   .cursor/rules/ (directory)          -> design-system-rules.mdc written
 *     whole, with the frontmatter Cursor expects.
 *   .windsurfrules                      -> COMPACT rules injected (Windsurf
 *     caps rules files at a few thousand characters). Injected only when the
 *     file already exists; .windsurf/rules/ (directory) gets its own file.
 *   .github/copilot-instructions.md     -> COMPACT rules injected; created
 *     when .github/ exists (Copilot chat and code review read this file, and
 *     Copilot's guidance prefers short instructions).
 * If none exist, falls back to design-system-rules.md at the root and says so.
 *
 *   node src/rules/apply.mjs <harvest.json> --target <repo-root>
 */
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { rulesMarkdown } from './build.mjs';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const inPath = process.argv[2] && !process.argv[2].startsWith('--') ? resolve(process.argv[2]) : null;
if (!inPath) { console.error('Usage: node src/rules/apply.mjs <harvest.json> --target <repo-root>'); process.exit(1); }
const target = resolve(arg('target', '.'));

const BEGIN = '<!-- roast-my-design-system:rules:begin (generated from a scan; this block is replaced by --apply, text outside it is never touched) -->';
const END = '<!-- roast-my-design-system:rules:end -->';

const h = JSON.parse(readFileSync(inPath, 'utf8'));
const { text, ruleCount } = rulesMarkdown(h);
// Size-aware variant for hosts with tight practical limits (Windsurf, Copilot)
const compactText = rulesMarkdown(h, { compact: true }).text;
const blockOf = (t) => `${BEGIN}\n\n${t.trim()}\n\n${END}`;
const block = blockOf(text);

/** Inject or replace our marked block in an existing file's content. */
function inject(content, b0 = block) {
  const b = content.indexOf(BEGIN);
  const e = content.indexOf(END);
  if (b !== -1 && e !== -1 && e > b) {
    return { next: content.slice(0, b) + b0 + content.slice(e + END.length), how: 'replaced' };
  }
  const sep = content.length === 0 ? '' : content.endsWith('\n\n') ? '' : content.endsWith('\n') ? '\n' : '\n\n';
  return { next: content + sep + b0 + '\n', how: 'added' };
}

const done = [];
for (const name of ['CLAUDE.md', 'AGENTS.md', '.cursorrules']) {
  const p = join(target, name);
  if (!existsSync(p) || !statSync(p).isFile()) continue;
  const { next, how } = inject(readFileSync(p, 'utf8'));
  writeFileSync(p, next);
  done.push(`${name} (${how} the rules block)`);
}

const cursorDir = join(target, '.cursor', 'rules');
if (existsSync(cursorDir) && statSync(cursorDir).isDirectory()) {
  const p = join(cursorDir, 'design-system-rules.mdc');
  const existed = existsSync(p);
  writeFileSync(p, `---\ndescription: Design system rules generated by roast-my-design-system from a scan of this repo\nalwaysApply: true\n---\n\n${text.trim()}\n`);
  done.push(`.cursor/rules/design-system-rules.mdc (${existed ? 'rewritten' : 'created'})`);
}

// Windsurf: the compact variant, because .windsurfrules has a hard character
// cap. Injected only into a file the user already has; a .windsurf/rules/
// directory gets its own file, same as Cursor's.
const windsurfFile = join(target, '.windsurfrules');
if (existsSync(windsurfFile) && statSync(windsurfFile).isFile()) {
  const { next, how } = inject(readFileSync(windsurfFile, 'utf8'), blockOf(compactText));
  writeFileSync(windsurfFile, next);
  done.push(`.windsurfrules (${how} the compact rules block)`);
}
const windsurfDir = join(target, '.windsurf', 'rules');
if (existsSync(windsurfDir) && statSync(windsurfDir).isDirectory()) {
  const p = join(windsurfDir, 'design-system-rules.md');
  const existed = existsSync(p);
  writeFileSync(p, `${compactText.trim()}\n`);
  done.push(`.windsurf/rules/design-system-rules.md (${existed ? 'rewritten' : 'created'})`);
}

// Copilot chat and code review read .github/copilot-instructions.md, and
// Copilot's guidance prefers short instructions: compact variant, created
// when .github/ exists (a strong signal the repo lives on GitHub).
const githubDir = join(target, '.github');
if (existsSync(githubDir) && statSync(githubDir).isDirectory()) {
  const p = join(githubDir, 'copilot-instructions.md');
  const existing = existsSync(p) && statSync(p).isFile() ? readFileSync(p, 'utf8') : '';
  const { next, how } = inject(existing, blockOf(compactText));
  writeFileSync(p, next);
  done.push(`.github/copilot-instructions.md (${existing ? `${how} the compact rules block` : 'created'})`);
}

if (done.length === 0) {
  const p = join(target, 'design-system-rules.md');
  writeFileSync(p, text);
  console.log(`No agent file found (CLAUDE.md, AGENTS.md, .cursorrules, .cursor/rules/, .windsurfrules, .github/).`);
  console.log(`✓ Wrote design-system-rules.md instead; point your agent at it.`);
} else {
  console.log(`✓ ${ruleCount} rules applied, every one with a receipt:`);
  for (const d of done) console.log(`  → ${d}`);
}
