#!/usr/bin/env node
/**
 * Apply — injects the generated agent rules straight into the files agents
 * already read, so the npx path ends where the skill's conversational merge
 * ends: rules in place, zero copy-paste.
 *
 * Targets, all that exist at the repo root:
 *   CLAUDE.md, AGENTS.md, .cursorrules  -> rules injected inside a marked
 *     block; re-running replaces only our block, never touching their text.
 *   .cursor/rules/ (directory)          -> design-system-rules.mdc written
 *     whole, with the frontmatter Cursor expects.
 * If none exist, falls back to design-system-rules.md at the root and says so.
 *
 *   node src/rules/apply.mjs <harvest.json> --target <repo-root>
 */
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { rulesMarkdown } from './build.mjs';

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i > -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const inPath = process.argv[2] && !process.argv[2].startsWith('--') ? resolve(process.argv[2]) : null;
if (!inPath) { console.error('Usage: node src/rules/apply.mjs <harvest.json> --target <repo-root>'); process.exit(1); }
const target = resolve(arg('target', '.'));

const BEGIN = '<!-- roast-my-design-system:rules:begin (generated from a scan; this block is replaced by --apply, text outside it is never touched) -->';
const END = '<!-- roast-my-design-system:rules:end -->';

const h = JSON.parse(readFileSync(inPath, 'utf8'));
const { text, ruleCount } = rulesMarkdown(h);
const block = `${BEGIN}\n\n${text.trim()}\n\n${END}`;

/** Inject or replace our marked block in an existing file's content. */
function inject(content) {
  const b = content.indexOf(BEGIN);
  const e = content.indexOf(END);
  if (b !== -1 && e !== -1 && e > b) {
    return { next: content.slice(0, b) + block + content.slice(e + END.length), how: 'replaced' };
  }
  const sep = content.length === 0 ? '' : content.endsWith('\n\n') ? '' : content.endsWith('\n') ? '\n' : '\n\n';
  return { next: content + sep + block + '\n', how: 'added' };
}

const done = [];
for (const name of ['CLAUDE.md', 'AGENTS.md', '.cursorrules']) {
  const p = join(target, name);
  if (!existsSync(p) || !statSync(p).isFile()) continue;
  const { next, how } = inject(readFileSync(p, 'utf8'));
  writeFileSync(p, next);
  done.push(`${name} (${how} the rules block)`);
}

const cursorDir = join(target, '.cursor', 'rules');
if (existsSync(cursorDir) && statSync(cursorDir).isDirectory()) {
  const p = join(cursorDir, 'design-system-rules.mdc');
  const existed = existsSync(p);
  writeFileSync(p, `---\ndescription: Design system rules generated by roast-my-design-system from a scan of this repo\nalwaysApply: true\n---\n\n${text.trim()}\n`);
  done.push(`.cursor/rules/design-system-rules.mdc (${existed ? 'rewritten' : 'created'})`);
}

if (done.length === 0) {
  const p = join(target, 'design-system-rules.md');
  writeFileSync(p, text);
  console.log(`No agent file found (CLAUDE.md, AGENTS.md, .cursorrules, .cursor/rules/).`);
  console.log(`✓ Wrote design-system-rules.md instead; point your agent at it.`);
} else {
  console.log(`✓ ${ruleCount} rules applied, every one with a receipt:`);
  for (const d of done) console.log(`  → ${d}`);
}
