/**
 * Rules builder — shared by the rules CLI and the diagnose page (which embeds
 * the generated markdown behind the gift reveal). Input: a harvest object.
 * Output: { text, ruleCount } — paste-ready agent-rules markdown, every rule
 * with a receipt from the scanned repo.
 */
import { distinctTypefaces } from '../lib/typefaces.mjs';
import { nearColorPairs } from './../lib/nearpairs.mjs';
import { neverImportedComponents } from '../lib/neverimported.mjs';
import { VERSION } from '../lib/version.mjs';

export function rulesMarkdown(h, opts = {}) {
  // compact: the size-aware variant for agent files with tight practical
  // limits (.windsurfrules caps out at a few thousand characters and Copilot's
  // guidance prefers short instructions). Fewer receipts per rule, no prose
  // preamble, and a hard character budget as a safety net. Same rules, tighter.
  const compact = opts.compact === true;
  const CAP = { components: compact ? 5 : 8, dupes: compact ? 3 : 6 };
const repoName = h.profile?.name ?? 'this repo';
  const t = h.tokens ?? {};
  const reusable = (h.components ?? []).filter((c) => !c.isPage);
  const scanDate = (h.harvestedAt ?? '').slice(0, 10);
  
  const lines = [];
  const rule = (s) => lines.push(`- ${s}`);
  const section = (title) => lines.push('', `### ${title}`, '');
  
  lines.push('## Design system rules');
  lines.push('');
  if (!compact) {
    lines.push(`<!-- Generated by roast-my-design-system from a scan of ${repoName} on ${scanDate}.`);
    lines.push('     Paste into CLAUDE.md, .cursor/rules or AGENTS.md. Regenerate after big refactors:');
    lines.push('     npx roast-my-design-system@latest --rules');
    lines.push('     Door note: Codex and Cursor read AGENTS.md; Claude Code reads CLAUDE.md only.');
    lines.push('     If this lives in AGENTS.md, add the line "@AGENTS.md" to CLAUDE.md so Claude sees it too. -->');
    lines.push('');
  }
  // Mirror of the report's "no design system" banner: with almost no colour or
  // spacing signal there is nothing to derive receipts from, so the preamble
  // must not claim any. Keep the two universal defaults, labelled as defaults.
  const spacingSignal = (t.spacing ?? []).length + (t.tailwind?.spacing ?? []).filter((v) => v.value.startsWith('[')).length;
  const noSystemLikely = (t.colors ?? []).length === 0 || ((t.colors ?? []).length < 3 && spacingSignal === 0);
  lines.push(noSystemLikely
    ? (compact
      ? 'Too little styling found to derive repo-specific rules; these are universal defaults. Rescan once real UI lands.'
      : 'The scan found too little styling in this repo to derive repo-specific rules; there is most likely no design system in here yet. The rules below are universal defaults, not findings. Rescan once real UI lands and they will be rebuilt from receipts.')
    : (compact
      ? `Follow these rules when writing or editing UI in this repo; derived from a scan on ${scanDate}.`
      : 'Follow these rules when writing or editing UI in this repo. Every rule below was derived from a scan of this codebase, with real paths and usage counts.'));
  
  // ---------- tokens ----------
  const strays = (t.colors ?? []).filter((c) => !c.isToken);
  const tokenCount = (t.colors ?? []).filter((c) => c.isToken).length;
  if (t.tokenFile || (t.colors ?? []).length) {
    section('Colours and tokens');
    if (t.namespaces?.primary) {
      const nsLabel = t.namespaces.partner ? `\`--${t.namespaces.primary}-*\` and \`--${t.namespaces.partner}-*\` namespaces` : `\`--${t.namespaces.primary}-*\` namespace`;
      rule(`This system's tokens answer to the ${nsLabel}. Reach for an existing \`var(--...)\` from them before inventing any value.`);
      if (t.namespaces.others?.length) rule(`${t.namespaces.others.map((l) => `\`--${l}-*\``).join(', ')} ${t.namespaces.others.length === 1 ? 'is also' : 'are also'} present in the code. Before writing new references to ${t.namespaces.others.length === 1 ? 'it' : 'them'}, check whether this repo treats ${t.namespaces.others.length === 1 ? 'it' : 'them'} as current or as a migration source; when unsure, prefer \`--${t.namespaces.primary}-*\`.`);
    }
    if (t.tokenFile) {
      rule(`Design tokens live in \`${t.tokenFile}\`. Reach for an existing token before inventing any value.`);
      if (tokenCount && strays.length) rule(`Never hardcode colour values in components. The palette already has ${tokenCount} tokens; the scan still found ${strays.length} hardcoded colours sitting next to them. Do not add more.`);
      else rule('Never hardcode colour values in components; add a token first if one is genuinely missing.');
    } else if ((t.colors ?? []).length) {
      rule(`There is no token file yet. Until one exists, reuse the colours already in the codebase instead of introducing new ones (${t.colors.length} distinct colours are already in play).`);
    }
    const near = nearColorPairs(t.colors ?? []);
    if (near.length) rule(`Never eyeball a colour from memory: the scan found ${near.length} nearly identical pair${near.length === 1 ? '' : 's'} (like ${near[0].a.value} next to ${near[0].b.value}). Look the exact value up, or better, use its token.`);
    const ds = h.profile?.designSystem;
    if (ds?.kind && !['none', 'custom'].includes(ds.kind) && ds.confidence !== 'low') {
      rule(`This repo uses ${ds.name ?? ds.kind}${h.profile.uiDir ? `; its components live in \`${h.profile.uiDir}\`` : ''}. Prefer extending it over building parallel pieces.`);
    }
  }
  
  // ---------- canonical components ----------
  // Skip names that shadow framework components (their usage counts absorb the
  // framework's) and names defined in more than one file (ambiguous, and the
  // duplicates section already handles them).
  const FRAMEWORK_NAMES = new Set(['Link', 'Image', 'Head', 'Script', 'Form']);
  const nameCounts = new Map();
  for (const c of reusable) nameCounts.set(c.name, (nameCounts.get(c.name) ?? 0) + 1);
  const top = reusable
    .filter((c) => c.usageCount > 0 && !FRAMEWORK_NAMES.has(c.name) && nameCounts.get(c.name) === 1)
    .sort((a, b) => b.usageCount - a.usageCount).slice(0, CAP.components);
  if (top.length) {
    section('Canonical components');
    rule(compact
      ? 'Use these existing components instead of writing new ones:'
      : 'Use these existing components instead of writing new ones, the way this repo already uses them:');
    for (const c of top) {
      const props = !compact && c.propsHint?.named?.length ? ` · props: ${c.propsHint.named.slice(0, 4).join(', ')}` : '';
      lines.push(`  - \`<${c.name}>\` from \`${c.file}\` (used ${c.usageCount}x${props})`);
      // Golden example: the repo's own most common real usage, quoted with a
      // receipt. Full variant only; compact hosts trade examples for size.
      const ex = c.usageExample;
      if (!compact && ex) {
        lines.push(`    - most common usage, as in \`${ex.file}\` (matching ${ex.matches} of ${ex.total} usages): \`${ex.snippet}\``);
      }
    }
  }
  
  // ---------- duplicates to avoid ----------
  const dupes = h.duplicates?.exactDuplicates ?? [];
  const icons = h.duplicates?.iconCollisions ?? [];
  if (dupes.length || icons.length) {
    section('Known duplicates: do not make it worse');
    // No per-file usage data here, so rank by how shared the location looks;
    // when nothing stands out, do not guess a canonical.
    const sharedScore = (f) => (f.includes('packages/') ? 4 : 0) + (/\/ui\//.test(f) ? 2 : 0) + (f.includes('components/') ? 1 : 0) - (/\bapp\//.test(f) ? 2 : 0) - (f.includes('/icons/') ? 4 : 0);
    for (const d of dupes.slice(0, CAP.dupes)) {
      const files = d.files.map((f) => (typeof f === 'string' ? f : f.file));
      const ranked = [...files].sort((a, b) => sharedScore(b) - sharedScore(a));
      const clear = sharedScore(ranked[0]) > sharedScore(ranked[1]);
      if (d.wrapped) {
        rule(`\`<${d.name}>\` is defined twice and one wraps the other${clear ? `. Import \`${ranked[0]}\`` : ''}; do not create a third.`);
      } else if (clear) {
        rule(`\`<${d.name}>\` exists in ${files.length} places. Treat \`${ranked[0]}\` as canonical; do not import the other ${files.length === 2 ? 'copy' : 'copies'}, and never create another.`);
      } else {
        rule(`\`<${d.name}>\` exists in ${files.length} places (${files.slice(0, 2).map((f) => `\`${f}\``).join(', ')}). Match whichever the surrounding code already imports, and never create another.`);
      }
    }
    if (icons.length) rule(`Two icon sets collide on ${icons.length} name${icons.length === 1 ? '' : 's'}. Before adding any icon, check which set the surrounding file already imports and stay with it.`);
  }
  
  // ---------- never-imported components ----------
const neverImported = neverImportedComponents(h.components, h.profile?.uiDir);
if (neverImported.length >= 3) {
  section('Components nobody imports');
  rule(`${neverImported.length} components are defined but never imported (${neverImported.slice(0, 3).map((c) => `\`<${c.name}>\``).join(', ')}…). Before writing any new component, check this list first; adopt one or flag it for deletion instead of adding another.`);
}

// ---------- spacing ----------
  const arbitrary = t.tailwind?.arbitrary ?? [];
  const arbCount = arbitrary.reduce((s, a) => s + a.count, 0);
  const offScale = (t.spacing ?? []).length;
  if (t.tailwind?.spacing?.length || offScale || arbCount) {
    section('Spacing and sizing');
    if (t.tailwind?.spacing?.length) rule('Stay on the Tailwind spacing scale. If a gap looks wrong on a scale step, flag it instead of nudging by a pixel.');
    if (arbCount) rule(`No new arbitrary bracket values (\`p-[13px]\`, \`text-[10px]\`). The scan found ${arbCount} already. If a value repeats, it is a decision: name it as a token instead of writing the bracket again.`);
    if (offScale) rule(`Avoid new one-off CSS spacing values; ${offScale} off-scale value${offScale === 1 ? ' is' : 's are'} already in play.`);
  }
  
  // ---------- typography ----------
  const faces = distinctTypefaces(t.fontFamilies ?? []);
  if (faces.length) {
    section('Typography');
    rule(`The repo uses ${faces.length} typeface${faces.length === 1 ? '' : 's'}: ${faces.slice(0, 4).join(', ')}. Do not introduce another, and do not re-declare font stacks by hand; use the existing setup.`);
  }
  
  // ---------- styling discipline ----------
  section('Styling discipline');
  rule(`Never write ${reusable.length ? '`style={{ ... }}`' : 'inline `style="..."` attributes'} for static values; styling belongs to classes and tokens where the system can see it.`);
  if ((t.inlineStyles?.count ?? 0) > 0) lines.push(`  (${t.inlineStyles.count} static inline block${t.inlineStyles.count === 1 ? '' : 's'} already exist; do not add to them.)`);
  if ((t.important?.count ?? 0) >= 3) rule(`Never write !important; the scan found ${t.important.count} declaration${t.important.count === 1 ? '' : 's'} already. When a style does not apply, fix the selector or the source of the conflict instead of shouting over it.`);
  rule('Before styling anything new, look at a neighbouring component and match how it does it. Consistency with the repo beats personal preference.');
  
  lines.push('');
  if (compact) {
    lines.push(`*Compact rules by roast-my-design-system ver. ${VERSION}; the full set with receipts: npx roast-my-design-system --rules*`);
  } else {
    lines.push('---');
    lines.push(`*Generated by [roast-my-design-system](https://github.com/gregkozakiewicz/roast-my-design-system) ver. ${VERSION}. Rescan after refactors to keep these rules honest.*`);
  }
  lines.push('');
  let text = lines.join('\n');
  // Safety net for tight hosts: if a very messy repo still blows the budget,
  // cut at the last section boundary under the cap and say the set continues.
  const MAX_COMPACT = 5000;
  if (compact && text.length > MAX_COMPACT) {
    const cut = text.lastIndexOf('\n### ', MAX_COMPACT);
    if (cut > 0) {
      text = `${text.slice(0, cut).trimEnd()}\n\n*Trimmed to fit this file's limits; the full rules: npx roast-my-design-system --rules*\n`;
    }
  }
  const ruleCount = text.split('\n').filter((l) => l.startsWith('- ')).length;
  return { text, ruleCount };
}
